export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_SUCCESS'

export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_USER_BY_ID_SUCCES = 'GET_USER_BY_ID_SUCCES'
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL'

export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const GET_POSTS_BY_ID = 'GET_POSTS_BY_ID'

export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_SUCCESS= 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL= 'GET_COMMENTS_SUCCESS'

